project:
  type: website

website:
  title: "Dr. Tanishq Abraham's blog"
  twitter-card: true
  open-graph: true
  google-analytics: G-LRXD97FB1E
  site-url: https://www.tanishq.ai/blog
  description: "Dr. Tanishq Abraham's blog."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tmabraham
      - icon: twitter
        href: https://twitter.com/iScienceLuvr
      - icon: linkedin
        href: https://linkedin.com/in/tanishq-abraham-iscienceluvr/
      - icon: rss
        href: index.xml
format:
  html:
    theme: litera
    css: styles.css



